[uWSGI] getting INI configuration from uwsgi_conf.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3648]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.3 (32bit) on [Sat Apr 19 12:44:46 2014] ***
compiled with version: 4.6.3 on 19 April 2014 12:36:11
os: Linux-3.2.0-24-virtual #37-Ubuntu SMP Wed Apr 25 12:51:49 UTC 2012
nodename: springboard
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /home/sauravtom/stud.in_server_backend
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3922
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :5002 fd 3
Python version: 2.7.3 (default, Sep 26 2013, 20:26:19)  [GCC 4.6.3]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x9202350
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 127960 bytes (124 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x9202350 pid: 14035 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 14035)
spawned uWSGI worker 1 (pid: 14040, cores: 1)
[pid: 14040|app: 0|req: 1/1] 59.179.148.124 () {32 vars in 568 bytes} [Sat Apr 19 12:44:54 2014] GET /test => generated 277 bytes in 14 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 14040|app: 0|req: 2/2] 59.179.148.124 () {32 vars in 568 bytes} [Sat Apr 19 12:46:14 2014] GET /test => generated 277 bytes in 10 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
