[uWSGI] getting INI configuration from uwsgi_conf.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3648]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.3 (32bit) on [Sat Apr 19 12:44:46 2014] ***
compiled with version: 4.6.3 on 19 April 2014 12:36:11
os: Linux-3.2.0-24-virtual #37-Ubuntu SMP Wed Apr 25 12:51:49 UTC 2012
nodename: springboard
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /home/sauravtom/stud.in_server_backend
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3922
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :5002 fd 3
Python version: 2.7.3 (default, Sep 26 2013, 20:26:19)  [GCC 4.6.3]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x9202350
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 127960 bytes (124 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x9202350 pid: 14035 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 14035)
spawned uWSGI worker 1 (pid: 14040, cores: 1)
[pid: 14040|app: 0|req: 1/1] 59.179.148.124 () {32 vars in 568 bytes} [Sat Apr 19 12:44:54 2014] GET /test => generated 277 bytes in 14 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 14040|app: 0|req: 2/2] 59.179.148.124 () {32 vars in 568 bytes} [Sat Apr 19 12:46:14 2014] GET /test => generated 277 bytes in 10 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from uwsgi_conf.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3648]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.3 (32bit) on [Sun Apr 20 00:34:20 2014] ***
compiled with version: 4.6.3 on 19 April 2014 12:36:11
os: Linux-3.2.0-24-virtual #37-Ubuntu SMP Wed Apr 25 12:51:49 UTC 2012
nodename: springboard
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /home/sauravtom/stud.in_server_backend
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3922
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :5002 fd 3
Python version: 2.7.3 (default, Sep 26 2013, 20:26:19)  [GCC 4.6.3]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x9186350
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 127960 bytes (124 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "./app.py", line 10, in <module>
    from flask.ext.sqlalchemy import SQLAlchemy
  File "/usr/local/lib/python2.7/dist-packages/flask/exthook.py", line 87, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.sqlalchemy
unable to load app 0 (mountpoint='') (callable not found or import error)
Traceback (most recent call last):
  File "/home/sauravtom/stud.in_server_backend/app.py", line 10, in <module>
    from flask.ext.sqlalchemy import SQLAlchemy
  File "/usr/local/lib/python2.7/dist-packages/flask/exthook.py", line 87, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.sqlalchemy
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5769)
spawned uWSGI worker 1 (pid: 5774, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 5774|app: -1|req: -1/1] 59.179.133.150 () {32 vars in 582 bytes} [Sun Apr 20 00:34:24 2014] GET /test-upload => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
[uWSGI] getting INI configuration from uwsgi_conf.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3648]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.3 (32bit) on [Sun Apr 20 00:35:50 2014] ***
compiled with version: 4.6.3 on 19 April 2014 12:36:11
os: Linux-3.2.0-24-virtual #37-Ubuntu SMP Wed Apr 25 12:51:49 UTC 2012
nodename: springboard
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /home/sauravtom/stud.in_server_backend
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3922
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (:5002).
bind(): Address already in use [core/socket.c line 759]
--- no python application found, check your startup logs for errors ---
[pid: 5774|app: -1|req: -1/2] 59.179.133.150 () {32 vars in 582 bytes} [Sun Apr 20 00:35:53 2014] GET /test-upload => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Sun Apr 20 00:37:50 2014 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
[uWSGI] getting INI configuration from uwsgi_conf.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3648]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.3 (32bit) on [Sun Apr 20 00:38:10 2014] ***
compiled with version: 4.6.3 on 19 April 2014 12:36:11
os: Linux-3.2.0-24-virtual #37-Ubuntu SMP Wed Apr 25 12:51:49 UTC 2012
nodename: springboard
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /home/sauravtom/stud.in_server_backend
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3922
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :5002 fd 3
Python version: 2.7.3 (default, Sep 26 2013, 20:26:19)  [GCC 4.6.3]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x850a350
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 127960 bytes (124 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x850a350 pid: 6006 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 6006)
spawned uWSGI worker 1 (pid: 6011, cores: 1)
[pid: 6011|app: 0|req: 1/1] 59.179.133.150 () {32 vars in 582 bytes} [Sun Apr 20 00:38:15 2014] GET /test-upload => generated 277 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 6011|app: 0|req: 2/2] 59.179.133.150 () {30 vars in 535 bytes} [Sun Apr 20 00:38:23 2014] GET /add => generated 291 bytes in 2169 msecs (HTTP/1.1 500) 2 headers in 84 bytes (2 switches on core 0)
[pid: 6011|app: 0|req: 3/3] 59.179.133.150 () {32 vars in 566 bytes} [Sun Apr 20 00:40:18 2014] GET /add => generated 291 bytes in 9 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
Sun Apr 20 00:40:43 2014 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
[uWSGI] getting INI configuration from uwsgi_conf.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3648]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.3 (32bit) on [Sun Apr 20 00:42:44 2014] ***
compiled with version: 4.6.3 on 19 April 2014 12:36:11
os: Linux-3.2.0-24-virtual #37-Ubuntu SMP Wed Apr 25 12:51:49 UTC 2012
nodename: springboard
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /home/sauravtom/stud.in_server_backend
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3922
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :5002 fd 3
Python version: 2.7.3 (default, Sep 26 2013, 20:26:19)  [GCC 4.6.3]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x9b59350
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 127960 bytes (124 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x9b59350 pid: 6244 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 6244)
spawned uWSGI worker 1 (pid: 6249, cores: 1)
[pid: 6249|app: 0|req: 1/1] 115.244.44.244 () {26 vars in 375 bytes} [Sun Apr 20 00:49:29 2014] POST /upload => generated 291 bytes in 9371 msecs (HTTP/1.1 500) 2 headers in 84 bytes (856 switches on core 0)
[pid: 6249|app: 0|req: 2/2] 115.244.44.244 () {26 vars in 381 bytes} [Sun Apr 20 00:49:39 2014] POST /upload => generated 291 bytes in 8250 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1154 switches on core 0)
[pid: 6249|app: 0|req: 3/3] 115.244.44.244 () {26 vars in 379 bytes} [Sun Apr 20 00:49:48 2014] POST /upload => generated 291 bytes in 7866 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1130 switches on core 0)
[pid: 6249|app: 0|req: 4/4] 115.244.44.244 () {26 vars in 375 bytes} [Sun Apr 20 00:49:57 2014] POST /upload => generated 291 bytes in 9075 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1126 switches on core 0)
[pid: 6249|app: 0|req: 5/5] 59.179.133.150 () {30 vars in 551 bytes} [Sun Apr 20 00:50:06 2014] GET /test-upload => generated 277 bytes in 10 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 6249|app: 0|req: 6/6] 59.179.133.150 () {40 vars in 761 bytes} [Sun Apr 20 00:50:11 2014] POST /upload => generated 291 bytes in 3292 msecs (HTTP/1.1 500) 2 headers in 84 bytes (51 switches on core 0)
[pid: 6249|app: 0|req: 7/7] 59.179.133.150 () {34 vars in 604 bytes} [Sun Apr 20 00:50:22 2014] GET /test-upload => generated 277 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 6249|app: 0|req: 8/8] 59.179.133.150 () {30 vars in 480 bytes} [Sun Apr 20 00:50:23 2014] GET /favicon.ico => generated 233 bytes in 1 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 6249|app: 0|req: 9/9] 59.179.133.150 () {40 vars in 761 bytes} [Sun Apr 20 00:50:30 2014] POST /upload => generated 291 bytes in 3091 msecs (HTTP/1.1 500) 2 headers in 84 bytes (52 switches on core 0)
